amcl:
  ros__parameters:
    use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map.yaml"  # your map file

planner_server:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      plugins: ["terra-sense::TerrainLayer"]
      terrain_costmap_layer:
        plugin: "terra-sense::TerrainLayer"
        topic: "/terrain_class"
        default_cost: 0
local_costmap:
  local_costmap:
    ros__parameters:
      plugins: ["terra-sense::TerrainLayer"]
      terrain_costmap_layer:
        plugin: "terra-sense::TerrainLayer"
        topic: "/terrain_class"
        default_cost: 0
